### ISSUE TITLE
Complete server + JVM crash when players ride one another

### ISSUE THREAD

**Issue by Tempest-5ky** [ForwarD-NerN/PlayerLadder#1]
More or less what the title says! Here's the crashlog: https://mclo.gs/auD75BU
The server has an ungodly amount of mods so it's possible that it's a conflict, but i'm not sure what could cause it.

**Comment by ForwarD-NerN** [comment]
I don't think that I can fix it. This mod uses vanilla code, so if any other mod replaces it, I can't do anything.
