### ISSUE TITLE
crashes server on startup. 1.19.2

### ISSUE THREAD

**Issue by AnomalousDeity** [ForwarD-NerN/PlayerLadder#4]
Caused byorg.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [playerladder.mixins.json:EntityMixin from mod playerladder] from phase [DEFAULT] in config [playerladder.mixins.json] FAILED during APPLY

**Comment by ForwarD-NerN** [comment]
Can you please provide the full log/crash report.
