### ISSUE TITLE
[Forge 1.19.4] Crash with Bumblezone mod due to PlayerLadder overwrite mixin

### ISSUE THREAD

**Issue by TelepathicGrunt** [ForwarD-NerN/PlayerLadder#6]
Hello, I am the dev of Bumblezone mod and I came across a user that experienced a crash due to our mods being on together:
[latest.log](https://github.com/ForwarD-NerN/PlayerLadder/files/11748879/latest.log)

Looking at the log, our two mixins into Entity's method for setting the passenger's offset is conflicting.

My mixin here is a modifyVariable to be as small as I can get it as compatible with other mods as best I can.
https://github.com/TelepathicGrunt/Bumblezone/blob/1.19.2-Forge/src/main/java/com/telepathicgrunt/the_bumblezone/mixin/entities/EntityMixin.java#L35

PlayerLadder overwrites this method which is incredibly dangerous as it obliterates other mod's mixins as seen here with the crash caused by the conflict.
https://github.com/ForwarD-NerN/PlayerLadder/blob/7f439ec9ef072ce2d321241d161e144140a61903/src/main/java/ru/nern/playerladder/mixin/EntityMixin.java#L56C1-L67

Please adopt a variant of my mixin if you can so that both of our mods can work together again and your mod won't crash with anyone else over this method (hopefully)

**Comment by ForwarD-NerN** [comment]
Hello, thanks for reporting the issue. It should be fixed now, I will release the new version soon.
