### ISSUE TITLE
Change the position of the rider player

### ISSUE THREAD

**Issue by dermitkess** [ForwarD-NerN/PlayerLadder#9]
If possible, can you change the position of the rider player a little higher than it is now. I'm asking you to do this because the rider is blocking the view of the lower player.

**Comment by ForwarD-NerN** [comment]
In previous versions of Player Ladder, it was adjusted if you installed the mod on the client. In some minor 1.20 version Mojang changed the offset themselves and I think it's fine now. It blocks the view a little bit, but not as much as before.
